name: "Bug report"
description: "Something isn't working as expected"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill this in so we can reproduce quickly.

  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of `ragnarok version`"
      placeholder: "v1.1.2"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      description: "Output of `python --version`"
      placeholder: "Python 3.11.4"
    validations:
      required: true

  - type: input
    id: install
    attributes:
      label: Install command
      description: "How did you install?"
      placeholder: "pip install ragnarok-ai[cli,ollama]"
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command you ran
      description: "Paste the exact command"
      placeholder: "ragnarok --json evaluate --demo --limit 3"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "JSON output with status=pass"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / output
      description: "Paste logs/output (redact secrets)."
      render: shell
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Create a fresh venv
        2. pip install ragnarok-ai
        3. ragnarok evaluate --demo
    validations:
      required: false
